package com.learning.prestamo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Cliente implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Description("Cedula del cliente")
	@org.kie.api.definition.type.Label("Cedula")
	private java.lang.Integer cedula;
	@org.kie.api.definition.type.Description("Edad del cliente")
	@org.kie.api.definition.type.Label("Edad")
	private java.lang.Integer edad;
	@org.kie.api.definition.type.Description("Numero de cuenta del cliente")
	@org.kie.api.definition.type.Label("Cuenta")
	private java.lang.Integer cuenta;
	@org.kie.api.definition.type.Description("Tipo de Cuenta del cliente \nA=Ahorros\nTC=Tarjeta de credito\nC=Corriente\nNA=No tiene cuentas")
	@org.kie.api.definition.type.Label("Tipo Cuenta")
	private java.lang.String tipocuenta;
	@org.kie.api.definition.type.Description("Saldo de la cuenta")
	@org.kie.api.definition.type.Label("Saldo")
	private java.lang.Integer saldo;
	@org.kie.api.definition.type.Description("Presenta Mora en la cuenta?")
	@org.kie.api.definition.type.Label("Mora")
	private java.lang.Boolean mora;

	@org.kie.api.definition.type.Description(value = "Llave principal para persistencia de datos en db externa")
	@org.kie.api.definition.type.Label(value = "id")
	private java.lang.Long id;

	public Cliente() {
	}

	public java.lang.Integer getCedula() {
		return this.cedula;
	}

	public void setCedula(java.lang.Integer cedula) {
		this.cedula = cedula;
	}

	public java.lang.Integer getEdad() {
		return this.edad;
	}

	public void setEdad(java.lang.Integer edad) {
		this.edad = edad;
	}

	public java.lang.Integer getCuenta() {
		return this.cuenta;
	}

	public void setCuenta(java.lang.Integer cuenta) {
		this.cuenta = cuenta;
	}

	public java.lang.String getTipocuenta() {
		return this.tipocuenta;
	}

	public void setTipocuenta(java.lang.String tipocuenta) {
		this.tipocuenta = tipocuenta;
	}

	public java.lang.Integer getSaldo() {
		return this.saldo;
	}

	public void setSaldo(java.lang.Integer saldo) {
		this.saldo = saldo;
	}

	public java.lang.Boolean getMora() {
		return this.mora;
	}

	public void setMora(java.lang.Boolean mora) {
		this.mora = mora;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public Cliente(java.lang.Integer cedula, java.lang.Integer edad,
			java.lang.Integer cuenta, java.lang.String tipocuenta,
			java.lang.Integer saldo, java.lang.Boolean mora, java.lang.Long id) {
		this.cedula = cedula;
		this.edad = edad;
		this.cuenta = cuenta;
		this.tipocuenta = tipocuenta;
		this.saldo = saldo;
		this.mora = mora;
		this.id = id;
	}

}