package com.learning.prestamo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Solicitud implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Description("Numero de solicitud de prestamo")
	@org.kie.api.definition.type.Label("Id Solicitud")
	private java.lang.Integer idSolicitud;
	@org.kie.api.definition.type.Description("Monto de dinero solicitado")
	@org.kie.api.definition.type.Label("Monto Solicitado")
	private java.lang.Integer monto;
	@org.kie.api.definition.type.Description("Monto Final Aprobado")
	@org.kie.api.definition.type.Label("Monto Aprobado")
	private java.lang.Integer montoaprobado;
	public Solicitud() {
	}

	public java.lang.Integer getIdSolicitud() {
		return this.idSolicitud;
	}

	public void setIdSolicitud(java.lang.Integer idSolicitud) {
		this.idSolicitud = idSolicitud;
	}

	public java.lang.Integer getMonto() {
		return this.monto;
	}

	public void setMonto(java.lang.Integer monto) {
		this.monto = monto;
	}

	public java.lang.Integer getMontoaprobado() {
		return this.montoaprobado;
	}

	public void setMontoaprobado(java.lang.Integer montoaprobado) {
		this.montoaprobado = montoaprobado;
	}

	public Solicitud(java.lang.Integer idSolicitud, java.lang.Integer monto,
			java.lang.Integer montoaprobado) {
		this.idSolicitud = idSolicitud;
		this.monto = monto;
		this.montoaprobado = montoaprobado;
	}

}