package com.learning.prestamo;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
public class ValidacionDatos implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Description("Codigo del error")
	@org.kie.api.definition.type.Label("Codigo Error")
	private java.lang.Integer errorcode;
	@org.kie.api.definition.type.Description("Mensaje del código del error")
	@org.kie.api.definition.type.Label("Mensaje Error")
	private java.lang.String errormessage;

	@org.kie.api.definition.type.Description(value = "Llave principal para persistencia de datos en db externa")
	@org.kie.api.definition.type.Label(value = "id")
    @javax.persistence.GeneratedValue(strategy = javax.persistence.GenerationType.AUTO, generator = "VALIDACIONDATOS_ID_GENERATOR")
    @javax.persistence.Id
    @javax.persistence.SequenceGenerator(name = "VALIDACIONDATOS_ID_GENERATOR", sequenceName = "VALIDACIONDATOS_ID_SEQUENCE")
	private java.lang.Long id;

	public ValidacionDatos() {
	}

	public java.lang.Integer getErrorcode() {
		return this.errorcode;
	}

	public void setErrorcode(java.lang.Integer errorcode) {
		this.errorcode = errorcode;
	}

	public java.lang.String getErrormessage() {
		return this.errormessage;
	}

	public void setErrormessage(java.lang.String errormessage) {
		this.errormessage = errormessage;
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public ValidacionDatos(java.lang.Integer errorcode,
			java.lang.String errormessage, java.lang.Long id) {
		this.errorcode = errorcode;
		this.errormessage = errormessage;
		this.id = id;
	}

}