package com.learning.prestamo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ValidacionDatos implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public ValidacionDatos() {
    }




}